route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    slack_configs:
      - api_url: 'http://hooks.slack.com/services/T00000/B00000/XXXXXXXXXXXX'
        channel: '#your-channel-name'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
